// Images reference /assets/team/ folder.
// Place team photos there with matching filenames.
// If local images are missing, the component falls back to aqresearchs.com URLs,
// then to initials placeholders.

const BASE = '/assets/team';
const REMOTE = 'https://aqresearchs.com';

export const teamData = [
  {
    name: 'Manjunath Sathya',
    role: 'Founder & Managing Director',
    shortDesc: '15+ years in quantitative & qualitative research. Ex-Hansa Research, Intage, Market Xcel.',
    fullBio: `Manjunath Sathya is a seasoned market research professional with over 15 years of strong hands-on experience in both quantitative and qualitative research. He has worked with leading research organizations and brings deep expertise in managing large sample studies, multi-sector projects, and client-driven research execution.\n\nHis professional journey includes 8 years with Hansa Research, 1 year with Intage, 3 years with Market Xcel, and 1 year with Purple Audacity. Across these roles, he has successfully delivered projects spanning social research, automobile studies, FMCG research, consumer behavior studies, and other diverse domains.\n\nManjunath is highly skilled in managing multiple projects simultaneously while maintaining quality, timelines, and client expectations. He is multilingual and fluent in English, Kannada, Telugu, and Tamil.`,
    img: `${BASE}/manju.jpg`,
    fallbackImg: `${REMOTE}/manju.jpg`,
    languages: ['English', 'Kannada', 'Telugu', 'Tamil'],
  },
  {
    name: 'Jagadish R',
    role: 'Sr. Operations Manager',
    shortDesc: '12 years in field research. 8 years with Hansa Research. Multilingual field coordinator.',
    fullBio: `Jagadish is a market research professional with 12 years of experience, including 8 years with Hansa Research. He has a strong command of field operations across both quantitative and qualitative studies, ensuring smooth execution, respondent management, and adherence to research protocols.\n\nHe is known for his hands-on approach in coordinating field teams and maintaining quality standards across projects. Jagadish is multilingual and can communicate effectively in English, Hindi, Telugu, and Tamil, enabling efficient interaction with diverse respondents and stakeholders.`,
    img: `${BASE}/jagdish.jpg`,
    fallbackImg: `${REMOTE}/jagdish.jpg`,
    languages: ['English', 'Hindi', 'Telugu', 'Tamil'],
  },
  {
    name: 'Hemath Kumar',
    role: 'Operation Director',
    shortDesc: 'Defines clear operational directions to align marketing activities with business objectives.',
    fullBio: `Hemath Kumar leads operational direction at AQ Research, aligning all marketing activities with client business objectives and organizational goals. He brings structured thinking and strong coordination skills to multi-project environments, ensuring efficient delivery across the organization.`,
    img: `${BASE}/hemath.png`,
    fallbackImg: `${REMOTE}/hemath.png`,
  },
  {
    name: 'Jemsy N K',
    role: 'Operation Manager',
    shortDesc: '15 years in market research. Ex-GfK, Hansa Research, Market Xcel. 10+ years in political research.',
    fullBio: `Jemsy is a seasoned market research professional with 15 years of experience across field and operational research environments. He has worked with leading organizations such as GfK, Hansa Research, and Market Xcel, gaining strong hands-on expertise in managing complex field activities and multitasking within large research operations.\n\nHe brings over 10 years of specialized experience in political research, where he has demonstrated strong capabilities in field coordination, execution discipline, and operational leadership. Jemsy is recognized for his ability to manage multiple responsibilities efficiently while maintaining research quality and timelines.`,
    img: `${BASE}/jemsy.jpeg`,
    fallbackImg: `${REMOTE}/jemsy.jpeg`,
  },
  {
    name: 'Dhanush S',
    role: 'Business Development Manager',
    shortDesc: '8 years in business development. International experience across Dubai, Malaysia, and Bangkok.',
    fullBio: `Dhanush has 8 years of professional experience in business development, working with multinational environments across international markets including Dubai, Malaysia, and Bangkok. He has been actively involved in driving business growth, client relationship management, and market expansion initiatives.\n\nHis cross-border exposure has strengthened his understanding of global business practices, communication, and strategic coordination. Dhanush is known for his proactive approach, adaptability, and ability to support business development objectives in fast-paced multinational settings.`,
    img: `${BASE}/dhanush.jpg`,
    fallbackImg: `${REMOTE}/dhanush.jpg`,
  },
  {
    name: 'Chandana CL',
    role: 'Project Executive',
    shortDesc: 'Strives to achieve sustainable growth and make a positive impact through quality service delivery.',
    fullBio: `Chandana CL is a dedicated project executive who brings strong attention to detail and a quality-first approach to every assignment. She is committed to sustainable growth and ensuring client satisfaction through consistent, reliable execution.`,
    img: `${BASE}/chandana.jpeg`,
    fallbackImg: `${REMOTE}/chandana.jpeg`,
  },
  {
    name: 'Greeshma S',
    role: 'Project Executive',
    shortDesc: 'Focused on continuous innovation and delivering exceptional client service for long-term success.',
    fullBio: `Greeshma S is a project executive focused on driving continuous innovation within research operations. Her goals are aligned with delivering exceptional client service and contributing to long-term organizational success.`,
    img: `${BASE}/greeshma.jpeg`,
    fallbackImg: `${REMOTE}/greeshma.jpeg`,
  },
  {
    name: 'Sunil U',
    role: 'Project Executive',
    shortDesc: 'Provides a mix of qualitative and quantitative research for a comprehensive market view.',
    fullBio: `Sunil U brings a well-rounded research perspective, combining qualitative and quantitative approaches to deliver comprehensive insights. His mixed-method expertise helps clients gain a fuller picture of their market environment.`,
    img: `${BASE}/sunil.jpg`,
    fallbackImg: `${REMOTE}/sunil.jpg`,
  },
  {
    name: 'Vamshikrishna CH',
    role: 'Project Executive',
    shortDesc: 'Identifies and analyzes consumer trends and behaviors through robust research methodologies.',
    fullBio: `Vamshikrishna CH specializes in identifying and analyzing consumer trends, preferences, and behaviors through robust and structured research methodologies. He brings analytical discipline and thorough data handling to every project.`,
    img: `${BASE}/vamshi.jpg`,
    fallbackImg: `${REMOTE}/vamshi.jpg`,
  },
  {
    name: 'Aneesh B',
    role: 'Project Executive Leader',
    shortDesc: 'Detail-oriented growth-driven professional with strong communication and interpersonal skills.',
    fullBio: `Aneesh B is a detail-oriented and growth-driven professional recognized for strong communication and interpersonal skills. As a project executive leader, he coordinates team activities, maintains project standards, and drives toward measurable outcomes.`,
    img: `${BASE}/aneesh.png`,
    fallbackImg: `${REMOTE}/aneesh.png`,
  },
  {
    name: 'Sudarshan VR',
    role: 'Lead Developer',
    shortDesc: 'Self-learner updated with new IT trends. Designs & develops software, web and mobile applications.',
    fullBio: `Sudarshan VR is a self-driven technologist who stays current with the latest technologies and industry trends. He leads development efforts at AQ Research, designing and building software, web, and mobile applications that support the organization's research and business objectives.`,
    img: `${BASE}/sudarshan.jpg`,
    fallbackImg: `${REMOTE}/sudarshan.jpg`,
  },
  {
    name: 'Sarah Bi Bi R',
    role: 'Developer',
    shortDesc: 'Stays ahead of market changes by monitoring industry developments and emerging digital trends.',
    fullBio: `Sarah Bi Bi R is a developer committed to staying ahead of market changes by continuously monitoring industry developments and emerging trends. She contributes to the technology backbone of AQ Research's client-facing and operational systems.`,
    img: `${BASE}/sarah.jpg`,
    fallbackImg: `${REMOTE}/sarah.jpg`,
  },
  {
    name: 'Alfa Bi',
    role: 'Project Executive',
    shortDesc: 'Focused on optimizing performance, reducing costs, and aligning operations with business objectives.',
    fullBio: `Alfa Bi brings an operations-optimization mindset to project execution — reducing costs, improving efficiencies, and ensuring all activities are tightly aligned with business objectives and client expectations.`,
    img: `${BASE}/alfa.jpg`,
    fallbackImg: `${REMOTE}/alfa.jpg`,
  },
  {
    name: 'D. Avinash',
    role: 'Project Manager Operations',
    shortDesc: 'Drives operational excellence and manages cross-functional teams for outstanding project results.',
    fullBio: `D. Avinash is a results-oriented project manager who drives operational excellence across AQ Research's project portfolio. He manages cross-functional teams and ensures that each project is delivered with precision, quality, and on schedule.`,
    img: `${BASE}/Avinash.png`,
    fallbackImg: `${REMOTE}/Avinash.png`,
  },
];
